### ISSUE TITLE
Issue with DSM 7

### ISSUE THREAD

**Issue by fatbob01** [Christofo/sssAI#13]
Good morning,

After updating to DSM 7, sssAI is no longer working for me.  I suspect a change in camera ID or a permission issue.

I can no longer access the following to find the camera ID:

Open browser and go to: http://<nasip>:<port>/webapi/auth.cgi?api=SYNO.API.Auth&method=Login&version=2&account=<username>&passwd=<password>&session=SurveillanceStation&format=cookie

In the same browser on the same tab open this page:
http://<nasip):<port>/webapi/entry.cgi?api=SYNO.SurveillanceStation.Camera&method=List&version=2

I get {"error":{"code":103},"success":false} and {"error":{"code":105},"success":false}

Thanks for your help!

**Comment by Christofo** [comment]
I haven't updated to DSM yet and won't for a bit so I don't have a way to test. Can you open a ticket with Synology and inquire about any changes to the Surveillance Station API?

**Comment by fatbob01** [comment]
Basically sent me a link to their documentation...I'll close for now.  Thanks

**Comment by martinlindhe** [comment]
Investigating the same issue here (DSM 7 broke working sssai setup).
My cameras have NOT changed ID:s in the upgrade if that is of any help.

The issue instead seems to be that sssai fails to to store temporary files here


https://github.com/Christofo/sssAI/blob/f3855fe91bf7c099e57245bf2b58776ccc052bc6/app/main.py#L143-L145


```
08/25/2021 03:40:22 PM - DEBUG - http://nas:83 "POST /v1/vision/detection HTTP/1.1" 400 59                                            
08/25/2021 03:40:22 PM - DEBUG - Got result: {                                                                                        
  "success": false,                                                                                                                   
  "error": "invalid image file",                                                                                                      
  "duration": 0                                                                                                                       
}. Time: 0.016291004023514688s
```

**Comment by tsheldon** [comment]
I've got an update on this, and I'll try to work on a pull request, but not sure on timeframe.

Looks like in the auth request, "version=1" may have been deprecated in dsm 7.   I get a failure if I curl that path with version=1, but if I update to "version=6" it succeeds and I get the login cookies.  I *believe* that the version correlates with the major version of DSM, but in my experiments, only version=6 seems to work against dsm 7.  (versions 1-5, 7 all fail with code 103)

**Comment by martinlindhe** [comment]
@tsheldon Please see the API document here https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/SurveillanceStation/All/enu/Surveillance_Station_Web_API.pdf

The version number simply needs  to be increased per the API doc depending on what arguments you are using. In the case of sssAI, we use "account" (version 1+), "passwd" (version 1+) and "session" (version 1+).

https://github.com/Christofo/sssAI/blob/abb69a8d0d18075ffb5bdeda1e04e0825516207c/app/main.py#L69

**Comment by martinlindhe** [comment]
@tsheldon You are right tho! I can verify only "version=6" works with logging in on DSM 7 + SSS 8.2.9.

However I think we need someone on DSM6 to verify that the following URL would work to log in as well so we don't break DSM6 support.
Maybe @Christofo could verify since he said earlier he stayed on DSM6 for now?

This is the exact URL I mean:

```sh
curl "http://my-nas:5000/webapi/auth.cgi?api=SYNO.API.Auth&method=Login&version=6&account=username&passwd=password&session=SurveillanceStation"
```

**Comment by tsheldon** [comment]
Yep, plan is to send a PR that moves the unique API versions (and a couple of things from open requests) to ENV with the current defaults so nothing breaks.

**Comment by Christofo** [comment]
I'm not using sssAI anymore for my camera detections.. but happy to try and help still. On DSM6 changing to "version=6" I receive the following:

~~{"error":{"code":407},"success":false}~~

EDIT: Disregard - my IP was blocked from some earlier failed attempts. using "version=6" returns this:

{"data":{"is_portal_port":false,"sid":"tyJ0M5usvvsTZpobX82eMc1fk7Wzri7Z0H7EVITS1hc7ejTQHjVhOWeouMYtHb5V0AfVLzPRDR0nbJeHJxyMfQ"},"success":true}

Appears to work.

**Comment by tsheldon** [comment]
So - out of curiosity, since you're the repo owner, what _are_ you using for your camera detections now? :)

**Comment by Christofo** [comment]
I'm using [Frigate](https://github.com/blakeblackshear/frigate) in a docker container on my DS920+. I bought a USB Coral Accelerator and it works fantastic. IMO it is much better than deepstack. You can use something like Node-RED to trigger Surveillance Station. I've been meaning to write up a blog post on the whole setup. 

Also, in the latest version of Surveillance Station you can use action rules to trigger a motion detection event. If you are set on using this script I created, I would definitely take advantage of that.

**Comment by tsheldon** [comment]
I, for one, look forward to the blog post ... though, not to derail the bug thread too far, but if you already have Frigate running, why also use SSS?
