### ISSUE TITLE
threshold not used

### ISSUE THREAD

**Issue by CoooWeee** [Christofo/sssAI#8]
The threshold of the cameras is not used ATM. 
Maybe something like:
```
threshold = cameradata[f"{camera_id}"]["threshold"]
...
if not found and label in detection_labels and \
   sizex>min_sizex and \
   sizey>min_sizey and \
   confidence >= threshold :
````

**Comment by CoooWeee** [comment]
I did couple of changed to it. Check out PR: #9

**Comment by Christofo** [comment]
> I did couple of changed to it. If wished I could create a PR.

Yes, please do!
